name: Verify

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Test code
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and test
        run: |
          npm ci --quiet
          npm run test:cov
        env:
          ICOMFORT_USERNAME: ${{ secrets.ICOMFORT_USERNAME }}
          ICOMFORT_PASSWORD: ${{ secrets.ICOMFORT_PASSWORD }}
          ICOMFORT_GATEWAY_SERIAL: ${{ secrets.ICOMFORT_GATEWAY_SERIAL }}

  lint:
    name: Lint code
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install and lint
        run: |
          npm ci --quiet
          npm run lint
